name: PluginTeste
version: '${project.version}'
main: teste.pluginteste.PluginTeste
api-version: 1.18
authors: [ JaaumG ]
description: attempt to develop a minecraft plugin
website: https://github.com/JaaumG
depend: [SkinsRestorer]
commands:
    ping:
      description: Ping
      usage: /<command>
    gamemode:
      description: Trocar gamemode
      usage: /<command>
      aliases: gm
    fake:
      description: Trocar o nick
      usage: /<command> nickname
    heal:
      description: Curar-se ou curar outro jogador
      usage: /<command> [<player>]
    feed:
      description: Alimentar-se ou alimentar outro jogador
      usage: /<command> [<player>]
    tag:
